Repository AhnSeene/find-my-meme-frontend, pull requests merged in 2024-08, with the labels that each got.

#5 Feat/ 로그인 틀 만들기
  package-lock.json
  package.json
  src/pages/Login.css
  src/pages/Login.js
Labels: enhancement

#13 feat: 회원가입 기능 구현
  src/App.js
  src/pages/SignUp.js
  src/pages/signup.css
Labels: enhancement

#14 [Feat] 태그 선택 시 서버에 이미지 호출하는 코드 추가
  public/data.json
  public/images/image1.jpeg
  public/images/image2.jpeg
  public/images/image3.jpeg
  src/pages/Home.js
  src/pages/home.css
Labels: enhancement

#18 Feat/findmemepost 기능 구현
  package-lock.json
  package.json
  src/App.js
  src/pages/FindMeme.js
  src/pages/FindMemePost.js
  src/pages/findmemepost.css
Labels: enhancement

#20 [Feat] 마이페이지 기능 구현
  src/App.js
  src/components/Header.js
  src/components/Profile.js
  src/pages/MyPage.js
  src/pages/mypage.css
Labels: enhancement

#25 design: Navbar 화면에 고정되게 수정
  src/App.css
  src/components/Header.css
  src/components/Navbar.css
Labels: enhancement

#31 feat: findmemedetail페이지에 댓글 입력칸 추가, 댓글 관리 기능 구현
  src/pages/FindMemeDetail.js
  src/pages/findmemedetail.css
Labels: enhancement

#80 fix: Dockerfile nginx.config 위치 수정
  Dockerfile
Labels: bug

#82 rename: nginx.config 폴더 위치변경
  nginx/nginx.conf
Labels: bug

#83 fix: docker push tag name change
  .github/workflows/build-and-push.yml
  src/nginx/nginx.conf
Labels: bug

#99 feat: nginx.config에 .well-knon/acme-challeng경로 추가
  nginx/nginx.conf
Labels: enhancement

#100 feat: nginx.config https 관련 설정 추가
  nginx/nginx.conf
Labels: bug, enhancement

#101 feat: nginx.config https관련 주석 처리
  nginx/nginx.conf
Labels: bug
