Repository AhnSeene/find-my-meme-frontend, pull requests merged in 2025-02, with the labels that each got.

#113 [Feat] 반응형 ui 적용, react query 로 무한스크롤 기능 변경, 배포 nignx.conf 변경
  .github/workflows/build-and-push.yml
  .github/workflows/deploy.yml
  Dockerfile
  nginx/nginx.conf
  package-lock.json
  package.json
  src/App.js
  src/assets/logo.png
  src/components/Button.css
  src/components/Button.js
  src/components/Header.css
  src/components/Header.js
  src/components/MemeGrid.css
  src/components/MemeGrid.js
  src/components/MemeSlider.js
  src/components/MemeSwiper.css
  src/components/MemeSwiper.js
  src/components/MyInfo.js
  src/components/Navbar.css
  src/components/Navbar.js
  src/components/PrivateRoute.js
  src/components/Profile.js
  src/components/commentform.css
  src/components/memeSlider.css
  src/components/profile.css
  src/contexts/AuthContext.js
  src/contexts/api.js
  src/hooks/useInfiniteMemesQuery.js
  src/hooks/useInfiniteScroll.js
  src/hooks/useToggleLike.js
  src/index.js
  src/logo.svg
  src/nginx/nginx.conf
  src/pages/FindMemePost.js
  src/pages/Home.js
  src/pages/Login.css
  src/pages/Login.js
  src/pages/MemeDetail.js
  src/pages/MyPage.js
  src/pages/SignUp.js
  src/pages/TopMeme.css
  src/pages/TopMeme.js
  src/pages/UploadMeme.css
  src/pages/UploadMeme.js
  src/pages/home.css
  src/pages/memedetail.css
  src/pages/mypage.css
  src/pages/signup.css
Labels: enhancement

#116 [Feat] api 호출 변경
  src/components/TagSelector.js
  src/hooks/useInfiniteMemesQuery.js
Labels: bug

#117 fix: 찾았다 게시글 목록 api 호출 url 수정
  src/pages/FindMeme.js
Labels: bug

#119 Feat 이메일 중복검사 추가
  src/hooks/useInfiniteScroll.js
  src/pages/Login.js
  src/pages/SignUp.js
Labels: enhancement

#121 feat: 파일 업로드 방식을 Multipart 에서 PresignedURL을 사용하는 것으로 바꿈
  src/pages/UploadMeme.js
Labels: enhancement

#125 Fix: 이메일 중복검사 기능 구현
  src/pages/Login.js
  src/pages/SignUp.js
Labels: enhancement

#126 Fix: 이미지 너비 조정
  .github/workflows/build-and-push.yml
  public/findmymeme-favicon.png
  public/index.html
  src/components/CommentForm.js
  src/components/MemeGrid.css
  src/components/commentlist.css
  src/pages/UploadMeme.js
  src/pages/findmemedetail.css
  src/pages/findmemepost.css
  src/pages/home.css
  src/pages/memedetail.css
Labels: enhancement

#128 fix : findmeme에서 페이지 네이션 오류 수정
  src/pages/FindMeme.js
Labels: bug

#129 fix: 오류수정, 반응형 최적화, 이미지 너비 수정
  .github/workflows/build-and-push.yml
  public/findmymeme-favicon.png
  public/index.html
  src/components/CommentForm.js
  src/components/Header.js
  src/components/MemeGrid.css
  src/components/MemeGrid.js
  src/components/commentlist.css
  src/contexts/AuthContext.js
  src/pages/FindMeme.js
  src/pages/FindMemePost.js
  src/pages/Login.js
  src/pages/MemeDetail.js
  src/pages/SignUp.js
  src/pages/UploadMeme.js
  src/pages/findmemedetail.css
  src/pages/findmemepost.css
  src/pages/home.css
  src/pages/memedetail.css
Labels: bug, enhancement

#134 fix: 로그아웃 상태에서 밈 좋아요 버튼 작동 안하게 수정
  src/hooks/useToggleLike.js
Labels: bug

#135 feat: s3로 배포하도록 변경, nginx.conf제거, Dockerfile제거
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-and-push.yml
  .github/workflows/deploy.yml
  Dockerfile
  nginx/nginx.conf
Labels: enhancement

#136 feat: s3로 배포하도록 변경, nginx.conf제거, Dockerfile제거
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-and-push.yml
  .github/workflows/deploy.yml
  Dockerfile
  nginx/nginx.conf
Labels: enhancement

#137 fix: build-and-deploy.yml에서 npm ci시 CI=false 추가
  .github/workflows/build-and-deploy.yml
Labels: bug

#138 fix: build-and-deploy.yml에서 npm ci시 CI=false 추가
  .github/workflows/build-and-deploy.yml
Labels: bug

#139 fix: deploy.yml에서 cross-env를 통해 환경변수 전달
  .github/workflows/build-and-deploy.yml
Labels: bug

#140 fix: deploy.yml에서 cross-env를 통해 환경변수 전달
  .github/workflows/build-and-deploy.yml
Labels: bug
